export const getUsers = async(req, res) =>{
    try{

    }catch{
        console.log(error)
    }
}